In [1]:
import numpy as np

#Creating Numpy Array

In [2]:
a = np.array([1,2,3])
print(a)
print(a.dtype)

[1 2 3]
int64


In [3]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)
a2.ndim

[[1 2 3]
 [4 5 6]]
(2, 3)


2

In [4]:
#arange function syntax = np.arange(start:end:step)
a1 = np.arange(100,200,2)
print(a1)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]


In [5]:
#linspace function syntax = np.linspace(start, end, number of values)
a3 = np.linspace(0, 10, num=4)
print(a3)

[ 0.          3.33333333  6.66666667 10.        ]


In [6]:
#rand function syntex = np.random.rand(shape of array)
#will give a random numbers between 0 and 1
a4 = np.random.rand(2,2)
print(a4)

[[0.45075179 0.24428596]
 [0.5857931  0.7027857 ]]


In [7]:
#zeros function syntex = np. zeros(shape of array)
#will genrate array of zerows according to given shape
a5 = np.zeros((4,2))
print(a5)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
#ones function syntex = np. ones(shape of array)
#will genrate array of ones according to given shape
a6 = np.ones((3,5))
print(a6)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
a7 = np.identity(4)
print(a7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
a8 = np.eye(3,5)
print(a8)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [11]:
#full function syntex = full(shape, value)
a9 = np.full((2,2),4)
print(a9)

[[4 4]
 [4 4]]


#Indexing in Numpy

In [12]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
arr[1,3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


9

In [13]:
arr[0,1:7]

array([2, 3, 4, 5])

In [14]:
arr[:,1]

array([2, 7])

In [15]:
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr2)
arr2[1,1,:]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([7, 8])

#Reshaping Numpy array

In [16]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr4 = arr3.reshape(4,3)
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
arr5 = np.array([1,2,3,4,5,6,7,8])
arr6 = arr5.reshape(3,3)
print(arr6)

ValueError: ignored

In [18]:
arr7 = np.array([[1,2,3],[4,5,6]])
arr8 = arr7.reshape(-1)
print(arr8)

[1 2 3 4 5 6]


In [19]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
h1 = np.array([[1],[2],[3]])
h2 = np.array([[4],[5],[6]])
np.hstack([h1,h2,h1,h2])

array([[1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6]])

In [21]:
np.vstack([h1,h2,h1,h2])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

#Sorting and Seaching using Numpy

In [23]:
arr1 = np.array([3,2,0,1])
arr2 = np.array(['banana','cherry','apple'])
arr3 = np.array([[3,2,4],[5,0,1]])

print(np.sort(arr1))
print(np.sort(arr2))
print(np.sort(arr3))

[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


In [24]:
b = np.array([12,90,380,12,211])

print(np.where(b>12))
print(np.where(b == 12))
print(np.where(b%12 == 0))

c = np.array([[20,24],[21,23],[2,25]])

print(np.where(c>19))

(array([1, 2, 4]),)
(array([0, 3]),)
(array([0, 3]),)
(array([0, 0, 1, 1, 2]), array([0, 1, 0, 1, 1]))


#Operations on Numpy array

In [25]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 * list2)

TypeError: ignored

In [26]:
npa1 = np.array(list1)
npa2 = np.array(list2)
print(npa1 * npa2)

[ 4 10 18]


In [27]:
np.cos(npa1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [28]:
a = np.array([1,2,3])
b = a
b[0] = 111
print(a)

[111   2   3]


In [29]:
c = a.copy()
c[0] = 222
print(a)
print(c)

[111   2   3]
[222   2   3]


In [30]:
npa1 = np.array([[1,1,1],[2,2,2]])
npa2 = np.array([[2,2,2],[2,2,2],[2,2,2]])
print(npa1.shape, npa2.shape)
np.matmul(npa1,npa2)

(2, 3) (3, 3)


array([[ 6,  6,  6],
       [12, 12, 12]])

In [31]:
npa1 = np.random.rand(2,2)
print(npa1)
np.linalg.det(npa1) #find determinate of matrix

[[0.89397305 0.85429153]
 [0.06361    0.3826742 ]]


0.28775893963400434